<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>12.0</LangVersion>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageId>Discord.cs</PackageId>
        <Version>0.0.5-alpha</Version>
        <Title>Discord.cs</Title>
        <Authors>Defxult</Authors>
        <Description>A Discord API library.</Description>
        <PackageLicenseUrl>https://github.com/Defxult/discord.cs/blob/master/LICENSE</PackageLicenseUrl>
        <RepositoryUrl>https://github.com/Defxult/discord.cs</RepositoryUrl>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <IncludeSymbols>true</IncludeSymbols>
        <IncludeSource>true</IncludeSource>
        <PackageProjectUrl>https://github.com/Defxult/discord.cs</PackageProjectUrl>
        <PackageTags>discord discord-api discord-bot websocket gateway interactions slash-commands discord-library csharp dotnet library</PackageTags>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    </ItemGroup>

</Project>
