using System.Text.Json;
using System.Text.RegularExpressions;
using Discord.Channels.Abstractions;
using Discord.Channels.Models;
using Discord.Channels.Services;
using Discord.Net;
using Discord.Utility;
using Newtonsoft.Json;

namespace Discord.Models;

/// <summary>
/// Represents a Discord message.
/// </summary>
public class Message : IEquatable<Message>
{
    // DOCS: https://discord.com/developers/docs/resources/message
    
    /// <summary>
    /// ID of the message.
    /// </summary>
    [JsonProperty("id")]
    public ulong Id { get; init; }
    
    /// <summary>
    /// ID of the channel the message was sent in.
    /// </summary>
    [JsonProperty("channel_id")]
    public ulong ChannelId { get; init; }
    
    /// <summary>
    /// Author of this message. If you need the <see cref="Models.Member"/> object instead, see <see cref="Member"/>.
    /// </summary>
    [JsonProperty("author")]
    public required User Author { get; init; }
    
    /// <summary>
    /// Content of the message. Will be an empty string if <see cref="Intent.MessageContent"/> is disabled via
    /// the <see cref="Bot"/> constructor or Developer Portal.
    /// </summary>
    [JsonProperty("content")]
    public string Content { get; internal set; } = string.Empty;
    
    /// <summary>
    /// When the message was sent.
    /// </summary>
    [JsonProperty("timestamp")]
    public DateTime Timestamp { get; init; }
    
    /// <summary>
    /// When the message was last edited, or <c>null</c>, if never.
    /// </summary>
    [JsonProperty("edited_timestamp")]
    public DateTime? EditedTimestamp { get; internal set; }
    
    /// <summary>
    /// Whether this was a TTS message.
    /// </summary>
    [JsonProperty("tts")]
    public bool Tts { get; init; }

    /// <summary>
    /// Whether this message mentions everyone.
    /// </summary>
    [JsonProperty("mention_everyone")]
    public bool EveryoneMentioned { get; init; }

    /// <summary>
    /// Roles specifically mentioned in this message.
    /// </summary>
    public IReadOnlyList<Role> MentionedRoles
    {
        get
        {
            if (GuildId is not { } guildId || Bot.GetGuild(guildId) is not { } guild) return [];
            var linq = 
                from rId in _mentionedRoleIds
                let role = guild.GetRole(rId)
                where role is not null
                select role;
            return linq.ToList();
        }
    }
    [JsonProperty("mention_roles")] private List<ulong> _mentionedRoleIds = [];

    /// <summary>
    /// Any attached files.
    /// </summary>
    [JsonProperty("attachments")]
    public IReadOnlyCollection<MessageAttachment> Attachments { get; init; } = [];
    
    /// <summary>
    /// Embeds on the message.
    /// </summary>
    [JsonProperty("embeds")]
    public IReadOnlyList<Embed> Embeds { get; private set; } = [];

    /// <summary>
    /// Reactions to the message.
    /// </summary>
    public IReadOnlyList<Reaction> Reactions => _reactions;
    [JsonProperty("reactions")] internal List<Reaction> _reactions = [];
    
    /// <summary>
    /// Used for validating a message was sent. Either a <see langword="string"/> or <see langword="int"/> when received
    /// but type <see langword="string"/> is always used.
    /// </summary>
    [JsonProperty("nonce")]
    public string? Nonce { get; init; }
    
    /// <summary>
    /// Whether this message is pinned.
    /// </summary>
    [JsonProperty("pinned")]
    public bool IsPinned { get; init; }
    
    /// <summary>
    /// If the message is generated by a webhook, this is the webhook's ID.
    /// </summary>
    [JsonProperty("webhook_id")]
    public ulong? WebhookId { get; init; }
    
    /// <summary>
    /// Type of message.
    /// </summary>
    [JsonProperty("type")]
    public MessageType Type { get; init; }
    
    /// <summary>
    /// Sent with Rich Presence-related chat embeds.
    /// </summary>
    [JsonProperty("activity")]
    public MessageActivity? Activity { get; init; }
    
    /// <summary>
    /// Sent with Rich Presence-related chat embeds.
    /// </summary>
    [JsonProperty("application")]
    public MessageApplication? Application { get; init; }
    
    /// <summary>
    /// If the message is an Interaction or application-owned webhook, this is the ID of the application.
    /// </summary>
    [JsonProperty("application_id")]
    public ulong? ApplicationId { get; init; }

    /// <summary>
    /// Message flags.
    /// </summary>
    public IReadOnlyCollection<MessageFlag>? Flags => _flags != null ? Util.FromBitfield<MessageFlag>(_flags.Value) : null;
    [JsonProperty("flags")] private int? _flags;
    
    /// <summary>
    /// Data showing the source of a crosspost, channel follow add, pin, or reply message.
    /// </summary>
    [JsonProperty("message_reference")]
    public MessageReference? Reference { get; init; }
    
    /// <summary>
    /// Message associated with the <see cref="Reference"/>.
    /// </summary>
    [JsonProperty("message_snapshots")]
    public IReadOnlyCollection<MessageSnapshot> Snapshots { get; init; } = [];
    
    /// <summary>
    /// Message associated with the <see cref="Reference"/>.
    /// </summary>
    [JsonProperty("referenced_message")]
    public Message? ReferencedMessage { get; init; }
    
    // TODO
    // [JsonProperty("interaction_metadata")]
    
    // TODO
    // [JsonProperty("interaction")]
    
    /// <summary>
    /// Thread that was started from this message.
    /// </summary>
    [JsonProperty("thread")]
    public ThreadChannel? Thread { get; internal set; }
    
    // TODO
    // [JsonProperty("components")]
    
    /// <summary>
    /// Stickers that were sent with the message.
    /// </summary>
    [JsonProperty("sticker_items")]
    public IReadOnlyCollection<StickerItem>? StickerItems { get; init; }
    
    /// <summary>
    /// A generally increasing integer that represents the approximate position of the message in a thread.
    /// </summary>
    [JsonProperty("position")]
    public int? Position { get; init; }
    
    /// <summary>
    /// Data of the role subscription purchase or renewal.
    /// </summary>
    [JsonProperty("role_subscription_data")]
    public RoleSubscriptionData? SubscriptionData { get; init; }
    
    /// <summary>
    /// A poll.
    /// </summary>
    [JsonProperty("poll")]
    public Poll? Poll { get; init; }
    
    /// <summary>
    /// The call associated with the message.
    /// </summary>
    [JsonProperty("call")]
    public MessageCall? Call { get; init; }
    
    #region These fields are specific to the MESSAGE_CREATE/UPDATE events

    /// <summary>
    /// ID of the guild the message was sent in - unless it is an ephemeral message.
    /// </summary>
    [JsonProperty("guild_id")]
    public ulong? GuildId { get; init; }
    
    /// <summary>
    /// The <see cref="Author"/> of this message but returns their <see cref="Models.Member"/> object instead. Will be
    /// <c>null</c> for ephemeral messages and messages from webhooks.
    /// </summary>
    [JsonProperty("member")]
    public Member? Member { get; init; }

    /// <summary>
    /// Users specifically mentioned in the message.
    /// </summary>
    [JsonProperty("mentions")]
    public required IReadOnlyCollection<User> MentionedUsers { get; init; }

    #endregion

    #region CUSTOM

    /// <summary>
    /// Your bot instance.
    /// </summary>
    public Bot Bot { get; internal set; } = null!;

    /// <summary>
    /// Guild this message belongs to. Can be <c>null</c> if it's ephemeral or direct message.
    /// </summary>
    public Guild? Guild => GuildId.HasValue ? Bot.GetGuild(GuildId.Value) : null;

    /// <summary>
    /// Channel the message was sent in.
    /// </summary>
    public IMessageable Channel => (Bot.GetAnyChannel(ChannelId) as IMessageable)!;

    /// <summary>
    /// Channels mentioned in the message.
    /// </summary>
    [JsonProperty("mention_channels")]
    public IReadOnlyCollection<GuildChannel> MentionedChannels
    {
        // Note: This is a custom implementation because the discord version is way too limited.
        get
        {
            if (Content == string.Empty) return [];
            
            var channels = new List<GuildChannel>();
            var charsToRemove = new[] { "<", ">", "#" };
            var ids = new HashSet<ulong>();
            var matches = Regex.Matches(Content, @"<#\d{17,19}>");
            foreach (Match match in matches)
            {
                var value = match.Value;
                foreach (var ch in charsToRemove)
                    value = value.Replace(ch, string.Empty);
                ids.Add(ulong.Parse(value));
            }
            foreach (var id in ids)
                if (Bot.GetChannel(id) is { } channel)
                    channels.Add(channel);
            return channels;
        }
    }
    
    internal DateTime _expiration;

    #endregion
    
    private Message() { }

    public bool Equals(Message? other)
    {
        if (other is not null)
            return other.Id == Id;
        return false;
    }
    public override bool Equals(object? obj)
    {
        if (obj is Message m)
            return Equals(m);
        return false;
    }
    public override int GetHashCode() => Id.GetHashCode();
    public static bool operator ==(Message? left, Message? right) => Equals(left, right);
    public static bool operator !=(Message? left, Message? right) => !Equals(left, right);

    /// <summary>
    /// Add reactions to the message.
    /// </summary>
    /// <param name="emojis">Reactions/emojis to add.</param>
    public async Task AddReactionsAsync(params string[] emojis)
    {
        foreach (var emoji in emojis)
            await Bot._rest.CreateReactionAsync(ChannelId, Id, PartialEmoji.FromString(emoji));
    }
    
    /// <summary>
    /// Remove a reaction.
    /// </summary>
    /// <param name="emoji">Reaction/emoji to remove.</param>
    /// <param name="user">If set, the provide user's reaction will be removed. If <c>null</c>, the bots reaction will be
    /// removed instead.
    /// </param>
    public async Task RemoveReactionAsync(string emoji, User? user = null)
    {
        var pe = PartialEmoji.FromString(emoji);
        if (user is null)
            await Bot._rest.DeleteOwnReactionAsync(ChannelId, Id, pe);
        else
            await Bot._rest.DeleteUserReactionAsync(ChannelId, Id, pe, user);
    }
    
    /// <summary>
    /// Request the users that reacted to the message using the specified emoji.
    /// </summary>
    /// <param name="emoji">The reaction/emoji.</param>
    /// <param name="amount">Amount of users to request (100 max yielded per loop). Can be <c>null</c> to request
    /// <b>all</b> users, and depending on the amount of reacts it can take a while.
    /// </param>
    /// <param name="after">Request users whose accounts were created after the given date.</param>
    /// <param name="type">Type of reaction.</param>
    /// <returns>The requested amount of users.</returns>
    public async IAsyncEnumerable<ICollection<User>> UsersForReactionAsync(string emoji, int? amount = 100,
        DateTime? after = null,
        ReactionType type = ReactionType.Normal)
    {
        const int indefinite = -1;
        var remaining = amount ?? indefinite;

        var afterSnowflakeTime = after is not null ? Util.DateTimeToSnowflake(after.Value) : 0;
        var hasMore = true;
        var yielded = new List<User>();

        do
        {
            yielded.Clear();
            var requestAmount = remaining == indefinite ? 100 : Math.Min(remaining, 100);
            var users = await Bot._rest.GetReactionsAsync(ChannelId, Id, PartialEmoji.FromString(emoji), type,
                requestAmount, afterSnowflakeTime);
            if (users.Count < 100)
                hasMore = false;

            foreach (var user in users)
            {
                yielded.Add(user);
                if (remaining == indefinite) continue;

                remaining -= 1;
                if (remaining == 0)
                    hasMore = false;
            }

            afterSnowflakeTime = users.Last().Id;
            yield return yielded;
        } while (hasMore);
    }

    /// <summary>
    /// Removes all reactions.
    /// </summary>
    /// <param name="emoji">If set, removes all specified reactions/emojis.</param>
    public async Task RemoveAllReactionsAsync(string? emoji = null)
    {
        if (emoji is null)
            await Bot._rest.DeleteAllReactions(ChannelId, Id);
        else
            await Bot._rest.DeleteAllReactionsForEmoji(ChannelId, Id, PartialEmoji.FromString(emoji));
    }

    /// <summary>
    /// Retrieve a reaction on the message.
    /// </summary>
    /// <param name="emoji">The emoji that represents the reaction.</param>
    /// <returns>The reaction matching the provided emoji, or <c>null</c> if not found.</returns>
    /// <remarks>This will always be <c>null</c> if not used on a cached message. Meaning if used on a message that was sent and
    /// the message object is returned from that method, this will be <c>null</c>. Only when retrieved from the cache will this
    /// have a value. Example:
    /// <code>
    ///     var sent = await message.Channel.SendAsync("discord.cs");
    ///     await sent.AddReactionAsync("😎");
    ///     var reaction1 = sent.GetReaction("😎"); // Will be null
    ///
    ///
    /// 
    ///     var cached = bot.GetMessage(sent.Id);
    ///     var reaction2 = cached.GetReaction("😎"); // Contains the reaction
    /// </code>
    /// </remarks>
    public Reaction? GetReaction(string emoji)
    {
        var pe = PartialEmoji.FromString(emoji);
        if (_reactions.FirstOrDefault(r => r.Emoji.Equals(pe)) is { } reaction)
            return reaction;
        return null;
    }

    /// <summary>
    /// Reply to a message.
    /// </summary>
    /// <param name="content">Content of the message.</param>
    /// <param name="silent">If <c>true</c>, mentions will not provide a desktop or push notification.</param>
    /// <param name="tts">Whether this is a TTS message.</param>
    /// <param name="embeds">Embeds (max 10), up to 6000 characters total.</param>
    /// <param name="allowedMentions">Allowed mentions for the message.</param>
    /// <param name="stickers">Up to 3 stickers to send in the message.</param>
    /// <param name="poll">A poll.</param>
    /// <param name="files">Files to upload with the message.</param>
    /// <param name="suppressEmbeds">Whether embeds are suppressed.</param>
    /// <returns>The message that was sent.</returns>
    public async Task<Message> ReplyAsync(string? content = null, bool silent = false, bool tts = false,
        IEnumerable<Embed>? embeds = null,
        AllowedMentions? allowedMentions = null, IEnumerable<GuildSticker>? stickers = null, Poll? poll = null,
        ICollection<DFile>? files = null, bool suppressEmbeds = false) =>
        await ChannelServicer.SendAsync(Channel, content, silent, tts, embeds, allowedMentions, stickers, poll, files,
            ToReference(), suppressEmbeds);

    /// <summary>
    /// Edit the message.
    /// </summary>
    /// <param name="edit">A message edit instance.</param>
    /// <returns>The edited message.</returns>
    public async Task<Message> EditAsync(MessageEdit edit) =>
        await Bot._rest.EditMessage(ChannelId, Id, edit);
    
    /// <summary>
    /// Delete the message.
    /// </summary>
    /// <param name="after">Amount of time in <b>seconds</b> to wait before deleting the message.</param>
    /// <param name="reason">Reason for deleting the message. This is displayed in the audit-log.</param>
    /// <returns>The task. If <paramref name="after"/> is provided, the task can be started in the background and either
    /// be discarded or awaited to produce any errors.
    /// <code>
    ///     // await like normal
    ///     await message.DeleteAsync(5);
    ///
    /// 
    ///     var task = message.DeleteAsync(5);
    ///     // Continue and process other information...
    ///     // If you want to know about any errors, await it
    ///     await task;
    ///
    /// 
    ///     // Or fire and forget, discarding any errors
    ///     _ = message.DeleteAsync(5);
    /// </code>
    /// </returns>
    /// <remarks>Requires <see cref="Permission.ManageMessages"/>.</remarks>
    public Task DeleteAsync(int? after = null, string? reason = null)
    {
        if (after == null)
            return Bot._rest.DeleteMessageAsync(ChannelId, Id, reason);
        return Task.Run(async () =>
        {
            await Task.Delay(TimeSpan.FromSeconds(after.Value));
            await Bot._rest.DeleteMessageAsync(ChannelId, Id, reason);
        });
    }
    
    /// <summary>
    /// Publish the message to all following channels.
    /// </summary>
    /// <remarks>Requires <see cref="Permission.SendMessages"/>.</remarks>
    public async Task PublishAsync() =>
        await Bot._rest.CrosspostMessageAsync(ChannelId, Id);
    
    /// <summary>
    /// Create a thread from a message.
    /// </summary>
    /// <param name="name">Name of the thread (1-100 characters).</param>
    /// <param name="duration">When the thread will stop showing in the channel list after inactivity.</param>
    /// <param name="slowModeDelaySeconds">Amount of seconds a user has to wait before sending another message (1-21600),
    /// or <c>null</c> to disable it.
    /// </param>
    /// <param name="reason">Reason for creating the thread. This is displayed in the audit-log.</param>
    /// <returns>The created thread.</returns>
    /// <remarks>Only valid for messages that were created in a <see cref="TextChannel"/> or <see cref="AnnouncementChannel"/>.</remarks>
    public async Task<ThreadChannel> CreateThreadAsync(string name,
        ThreadArchiveDuration duration = ThreadArchiveDuration.ThreeDays, int? slowModeDelaySeconds = null,
        string? reason = null)
    {
        var payload = new JSON
        {
            { "name", name },
            { "auto_archive_duration", duration },
            { "rate_limit_per_user", slowModeDelaySeconds ?? 0 }
        };
        return await Bot._rest.StartThreadFromMessage(Guild!, ChannelId, Id, payload, reason);
    }

    private MessageReference ToReference() => 
        new (MessageReferenceType.Default, Id, ChannelId, GuildId, false);
}

/// <summary>
/// Represents the values that can be edited for a <see cref="Message"/>.
/// </summary>
public struct MessageEdit
{
    internal readonly JSON _payload = [];
    internal IEnumerable<DFile> _files = [];
    
    /// <summary>
    /// Initialize a new message edit instance.
    /// </summary>
    public MessageEdit() { }

    /// <summary>
    /// Set the message content.
    /// </summary>
    /// <param name="content"></param>
    /// <returns>The message edit instance.</returns>
    public MessageEdit SetContent(string content)
    {
        _payload["content"] = content;
        return this;
    }

    /// <summary>
    /// Set the embeds.
    /// </summary>
    /// <param name="embeds">Embeds to set.</param>
    /// <returns>The message edit instance.</returns>
    public MessageEdit SetEmbeds(IEnumerable<Embed> embeds)
    {
        _payload["embeds"] = embeds;
        return this;
    }

    /// <summary>
    /// Set attachments and or files.
    /// </summary>
    /// <param name="attachments">Any attachments you would like retained.</param>
    /// <param name="files">New files that will be attached.</param>
    /// <returns>The message edit instance.</returns>
    /// <remarks>
    /// Both <paramref name="attachments"/> and <paramref name="files"/> can be <c>null</c> to remove all attachments
    /// </remarks>
    public MessageEdit SetAttachments(IReadOnlyCollection<MessageAttachment>? attachments, IEnumerable<DFile>? files)
    {
        _payload["attachments"] = attachments ?? [];
        _files = files ?? [];
        return this;
    }

    /// <summary>
    /// Set whether embeds are suppressed.
    /// </summary>
    /// <param name="suppressed">If embeds are suppressed.</param>
    /// <returns>The message edit instance.</returns>
    public MessageEdit SetSuppressEmbeds(bool suppressed)
    {
        if (suppressed)
            _payload["flags"] = Util.FromFlags([MessageFlag.SuppressEmbeds]);
        else
            _payload["flags"] = 0;
        return this;
    }

    /// <summary>
    /// Set allowed mentions.
    /// </summary>
    /// <param name="allowedMentions">An allowed mentions object.</param>
    /// <returns>The message edit instance.</returns>
    public MessageEdit SetAllowedMentions(AllowedMentions? allowedMentions)
    {
        _payload["allowed_mentions"] = allowedMentions?.ToJson();
        return this;
    }
}

/// <summary>
/// Represents a call associated with a <see cref="Message"/>.
/// </summary>
public record MessageCall
{
    // DOCS: https://discord.com/developers/docs/resources/message#message-call-object
    
    /// <summary>
    /// IDs of the users that participated in the call.
    /// </summary>
    [JsonProperty("participants")]
    public required IReadOnlyCollection<User> Participants { get; init; }
    
    /// <summary>
    /// When the call ended.
    /// </summary>
    [JsonProperty("ended_timestamp")]
    public DateTime? EndedTimestamp { get; init; }
    
    private MessageCall() { }
}

/// <summary>
/// Represents a role subscription data for a <see cref="Message"/>.
/// </summary>
public record RoleSubscriptionData
{
    // DOCS: https://discord.com/developers/docs/resources/message#role-subscription-data-object
    
    /// <summary>
    /// ID of the sku and listing that the user is subscribed to.
    /// </summary>
    [JsonProperty("role_subscription_listing_id")]
    public ulong RoleSubscriptionListingId { get; init; }
    
    /// <summary>
    /// Name of the tier that the user is subscribed to.
    /// </summary>
    [JsonProperty("tier_name")]
    public required string TierName { get; init; }
    
    /// <summary>
    /// Cumulative number of months that the user has been subscribed for.
    /// </summary>
    [JsonProperty("total_months_subscribed")]
    public int TotalMonthsSubscribed { get; init; }
    
    /// <summary>
    /// Whether this notification is for a renewal rather than a new purchase.
    /// </summary>
    [JsonProperty("is_renewal")]
    public bool IsRenewal { get; init; }
    
    private RoleSubscriptionData() { }
}

/// <summary>
/// Represents a snapshot on a <see cref="Message"/>.
/// </summary>
public record MessageSnapshot
{
    // DOCS: https://discord.com/developers/docs/resources/message#message-snapshot-object
    
    /// <inheritdoc cref="Message.Type"/>
    [JsonProperty("type")]
    public MessageType Type { get; init; }
    
    /// <inheritdoc cref="Message.Content"/>
    [JsonProperty("content")]
    public string Content { get; internal set; } = string.Empty;
    
    /// <inheritdoc cref="Message.Embeds"/>
    [JsonProperty("embeds")]
    public IReadOnlyList<Embed> Embeds { get; private set; } = [];
    
    /// <inheritdoc cref="Message.Attachments"/>
    [JsonProperty("attachments")]
    public IReadOnlyCollection<MessageAttachment> Attachments { get; init; } = [];
    
    /// <inheritdoc cref="Message.Timestamp"/>
    [JsonProperty("timestamp")]
    public DateTime Timestamp { get; init; }
    
    /// <inheritdoc cref="Message.EditedTimestamp"/>
    [JsonProperty("edited_timestamp")]
    public DateTime? EditedTimestamp { get; internal set; }
    
    /// <inheritdoc cref="Message.Flags"/>
    public IReadOnlyCollection<MessageFlag>? Flags => _flags != null ? Util.FromBitfield<MessageFlag>(_flags.Value) : null;
    [JsonProperty("flags")] private int? _flags;

    /// <summary>
    /// IDs of the roles specifically mentioned in this message.
    /// </summary>
    [JsonProperty("mention_roles")]
    public IReadOnlyCollection<ulong> MentionedRoleIds { get; init; } = [];

    /// <inheritdoc cref="Message.StickerItems"/>
    [JsonProperty("sticker_items")]
    public IReadOnlyCollection<GuildSticker>? StickerItems { get; init; }
    
    // TODO
    // [JsonProperty("components")]
    
    private MessageSnapshot() { }
}

/// <summary>
/// Represents a partial application for a <see cref="Message"/>.
/// </summary>
public record MessageApplication
{
    /// <summary>
    /// Application ID.
    /// </summary>
    [JsonProperty("id")]
    public ulong Id { get; init; }
    
    /// <summary>
    /// Application name.
    /// </summary>
    [JsonProperty("name")]
    public required string Name { get; init; }
    
    /// <summary>
    /// Application description.
    /// </summary>
    [JsonProperty("description")]
    public required string Description { get; init; }
    
    private MessageApplication() { }
}

/// <summary>
/// Represents a <see cref="Message"/> selectable history.
/// </summary>
public enum MessageHistory
{
    Before,
    After,
    Around
}

/// <summary>
/// Represents an attachment on a <see cref="Message"/>.
/// </summary>
public class MessageAttachment : Downloadable
{
    // DOCS: https://discord.com/developers/docs/resources/message#attachment-object-attachment-structure
    
    /// <summary>
    /// Attachment ID.
    /// </summary>
    [JsonProperty("id")]
    public ulong Id { get; init; }

    /// <summary>
    /// Name of file attached.
    /// </summary>
    [JsonProperty("filename")]
    public required string Filename { get; init; }
    
    /// <summary>
    /// Description for the file (max 1024 characters).
    /// </summary>
    [JsonProperty("description")]
    public string? Description { get; init; }

    /// <summary>
    /// The attachment's media type.
    /// </summary>
    [JsonProperty("content_type")]
    public string? ContentType { get; init; }

    /// <summary>
    /// Size of file in bytes.
    /// </summary>
    [JsonProperty("size")]
    public int Size { get; init; }
    
    /// <summary>
    /// A proxied URL of file.
    /// </summary>
    [JsonProperty("proxy_url")]
    public required string ProxyUrl { get; init; }

    /// <summary>
    /// Height of file (if image).
    /// </summary>
    [JsonProperty("height")]
    public int? Height { get; init; }

    /// <summary>
    /// Width of file (if image).
    /// </summary>
    [JsonProperty("width")]
    public int? Width { get; init; }

    /// <summary>
    /// Whether this attachment is ephemeral.
    /// </summary>
    [JsonProperty("ephemeral")]
    public bool Ephemeral { get; init; }

    /// <summary>
    /// The duration of the audio file (currently for voice messages).
    /// </summary>
    [JsonProperty("duration_secs")]
    public double? Duration { get; init; }

    /// <summary>
    /// A bytearray representing a sampled waveform (currently for voice messages).
    /// </summary>
    public byte[]? Waveform => _waveform != null ? Convert.FromBase64String(_waveform) : null; 
    [JsonProperty("waveform")] private string? _waveform;

    /// <summary>
    /// The attachments flags.
    /// </summary>
    public readonly IReadOnlyCollection<MessageAttachmentFlag> Flags;

    [JsonConstructor]
    internal MessageAttachment(int flags)
    {
        Flags = Util.FromBitfield<MessageAttachmentFlag>(flags);
    }
}

/// <summary>
/// Represents the flags for a <see cref="MessageAttachment"/>.
/// </summary>
[Flags]
public enum MessageAttachmentFlag
{
    // DOCS: https://discord.com/developers/docs/resources/message#attachment-object-attachment-flags
    
    /// <summary>
    /// This attachment has been edited using the remix feature on mobile.
    /// </summary>
    IsRemix = 1 << 2
}

/// <summary>
/// Represents a <see cref="Message"/> type.
/// </summary>
public enum MessageType
{
    // DOCS: https://discord.com/developers/docs/resources/message#message-object-message-types
    
    Default,
    RecipientAdd,
    RecipientRemove,
    Call,
    ChannelNameChange,
    ChannelIconChange,
    ChannelPinnedMessage,
    UserJoin,
    GuildBoost,
    GuildBoostTier1,
    GuildBoostTier2,
    GuildBoostTier3,
    ChannelFollowAdd,
    GuildDiscoveryDisqualified = 14,
    GuildDiscoveryRequalified,
    GuildDiscoveryGracePeriodInitialWarning,
    GuildDiscoveryGracePeriodFinalWarning,
    ThreadCreated,
    Reply,
    ChatInputCommand,
    ThreadStarterMessage,
    GuildInviteReminder,
    ContextMenuCommand,
    AutoModerationAction,
    RoleSubscriptionPurchase,
    InteractionPremiumUpsell,
    StageStart,
    StageEnd,
    StageSpeaker,
    StageTopic = 31,
    GuildApplicationPremiumSubscription,
    GuildIncidentAlertModeEnabled = 36,
    GuildIncidentAlertModeDisabled,
    GuildIncidentReportRaid,
    GuildIncidentReportFalseAlarm,
    PurchaseNotification = 44,
    PollResult = 46
}

/// <summary>
/// Represents a <see cref="Message"/> activity.
/// </summary>
public record MessageActivity
{
    // DOCS: https://discord.com/developers/docs/resources/message#message-object-message-activity-structure
    
    /// <summary>
    /// Type of message activity.
    /// </summary>
    [JsonProperty("type")]
    public MessageActivityType Type { get; init; }

    /// <summary>
    /// Party ID from a Rich Presence event.
    /// </summary>
    [JsonProperty("party_id")]
    public string? PartyId { get; init; }
    
    private MessageActivity() { }
}

/// <summary>
/// Represents a <see cref="MessageActivity"/> type.
/// </summary>
public enum MessageActivityType
{
    // DOCS: https://discord.com/developers/docs/resources/message#message-object-message-activity-types
    
    Join = 1,
    Spectate,
    Listen,
    JoinRequest	= 5
}

/// <summary>
/// Represents the flags on a <see cref="Message"/>.
/// </summary>
[Flags]
public enum MessageFlag
{
    // DOCS: https://discord.com/developers/docs/resources/message#message-object-message-flags
    
    /// <summary>
    /// This message has been published to subscribed channels (via Channel Following).
    /// </summary>
    Crossposted                      = 1 << 0,
    
    /// <summary>
    /// This message originated from a message in another channel (via Channel Following).
    /// </summary>
    IsCrossposted                    = 1 << 1,
    
    /// <summary>
    /// Do not include any embeds when serializing this message.
    /// </summary>
    SuppressEmbeds                   = 1 << 2,
    
    /// <summary>
    /// The source message for this crosspost has been deleted (via Channel Following).
    /// </summary>
    SourceMessageDeleted             = 1 << 3,
    
    /// <summary>
    /// This message came from the urgent message system.
    /// </summary>
    Urgent                           = 1 << 4,
    
    /// <summary>
    /// This message has an associated thread, with the same ID as the message.
    /// </summary>
    HasThread                        = 1 << 5,
    
    /// <summary>
    /// This message is only visible to the user who invoked the Interaction.
    /// </summary>
    Ephemeral                        = 1 << 6,
    
    /// <summary>
    /// This message is an Interaction Response and the bot is "thinking".
    /// </summary>
    Loading                          = 1 << 7,
    
    /// <summary>
    /// This message failed to mention some roles and add their members to the thread.
    /// </summary>
    FailedToMentionSomeRolesInThread = 1 << 8,
    
    /// <summary>
    /// This message will not trigger push and desktop notifications.
    /// </summary>
    SuppressNotifications            = 1 << 12,
    
    /// <summary>
    /// This message is a voice message.
    /// </summary>
    IsVoiceMessage                   = 1 << 13,
    
    /// <summary>
    /// This message has a snapshot (via Message Forwarding).
    /// </summary>
    HasSnapshot                      = 1 << 14,
    
    /// <summary>
    /// allows you to create fully component-driven messages.
    /// </summary>
    IsComponentsV2                   = 1 << 15
}

/// <summary>
/// Represents a <see cref="Message"/> reference.
/// </summary>
public record MessageReference
{
    // DOCS: https://discord.com/developers/docs/resources/message#message-reference-object
    
    /// <summary>
    /// Type of reference.
    /// </summary>
    [JsonProperty("type")]
    public MessageReferenceType? Type { get; init; }
    
    /// <summary>
    /// ID of the originating message.
    /// </summary>
    [JsonProperty("message_id")]
    public ulong? MessageId { get; init; }

    /// <summary>
    /// ID of the originating message's channel.
    /// </summary>
    [JsonProperty("channel_id")]
    public ulong? ChannelId { get; init; }

    /// <summary>
    /// ID of the originating message's guild.
    /// </summary>
    [JsonProperty("guild_id")]
    public ulong? GuildId { get; init; }

    /// <summary>
    /// When sending, whether to error if the referenced message doesn't exist instead of sending as a normal (non-reply) message.
    /// </summary>
    [JsonProperty("fail_if_not_exists")]
    public bool? FailIfNotExists { get; init; }
    
    private MessageReference() { }

    internal MessageReference(MessageReferenceType type, ulong? messageId, ulong? channelId, ulong? guildId,
        bool failIfNotExists)
    {
        Type = type;
        MessageId = messageId;
        ChannelId = channelId;
        GuildId = guildId;
        FailIfNotExists = failIfNotExists;
    }
}

/// <summary>
/// Represents a <see cref="MessageReference"/> type.
/// </summary>
public enum MessageReferenceType
{
    // DOCS: https://discord.com/developers/docs/resources/message#message-reference-types
    
    /// <summary>
    /// A standard reference used by replied.
    /// </summary>
    Default,
    
    /// <summary>
    /// Reference used to point to a message at a point in time.
    /// </summary>
    Forward
}

/// <summary>
/// Represents what mentions are allowed in a <see cref="Message"/>.
/// </summary>
public record struct AllowedMentions
{
    // DOCS: https://discord.com/developers/docs/resources/message#allowed-mentions-object
    
    /// <summary>
    /// If users can be mentioned in a message.
    /// </summary>
    public bool Users { get; set; }

    /// <summary>
    /// If roles can be mentioned in a message.
    /// </summary>
    public bool Roles { get; set; }

    /// <summary>
    /// If the user to the message that is being replied to are allowed to be mentioned in a message.
    /// </summary>
    public bool RepliedUser { get; set; }

    /// <summary>
    /// If <c>@everyone</c> or <c>@here</c> are allowed to be mentioned in a message.
    /// </summary>
    public bool Everyone { get; set; }

    /// <summary>
    /// The <b>only</b> users that can be mentioned in a message.
    /// </summary>
    public HashSet<User> ExemptUsers { get; set; } = [];

    /// <summary>
    /// The <b>only</b> roles that can be mentioned in a message.
    /// </summary>
    public HashSet<Role> ExemptRoles { get; set; } = [];

    /// <summary>
    /// Initializes a new allowed mentions instance with its fields set to the equivalent of <see cref="AllowedMentions.Default"/>.
    /// </summary>
    public AllowedMentions()
    {
        Users = true;
        Roles = false;
        RepliedUser = true;
        Everyone = false;
    }

    /// <summary>
    /// Initializes a new allowed mentions instance.
    /// </summary>
    /// <param name="users">If users can be mentioned in a message.</param>
    /// <param name="roles">If roles can be mentioned in a message.</param>
    /// <param name="repliedUser">If the user to the message that is being replied to are allowed to be mentioned in a message.</param>
    /// <param name="everyone">If <c>@everyone</c> or <c>@here</c> are allowed to be mentioned in a message.</param>
    public AllowedMentions(bool users, bool roles, bool repliedUser, bool everyone)
    {
        Users = users;
        Roles = roles;
        RepliedUser = repliedUser;
        Everyone = everyone;
    }

    /// <summary>
    /// Returns an <see cref="AllowedMentions"/> with all of its fields set to <c>true</c>.
    /// </summary>
    public static readonly AllowedMentions All = new(users: true, roles: true, repliedUser: true, everyone: true);

    /// <summary>
    /// Returns an <see cref="AllowedMentions"/> with its fields set to:
    /// <list type="bullet">
    ///     <item><c>Users = true</c></item>
    ///     <item><c>Roles = false</c></item>
    ///     <item><c>RepliedUser = true</c></item>
    ///     <item><c>Everyone = false</c></item>
    /// </list>
    /// </summary>
    public static readonly AllowedMentions Default = new();

    /// <summary>
    /// Returns an <see cref="AllowedMentions"/> with all of its fields set to <c>false</c>.
    /// </summary>
    public static readonly AllowedMentions None = new(users: false, roles: false, repliedUser: false, everyone: false);

    internal JSON ToJson()
    {
        var parse = new List<string>();

        if (Users)
            parse.Add("users");
        if (Roles)
            parse.Add("roles");
        if (Everyone)
            parse.Add("everyone");

        // "users" & "roles" must be removed or else an invalidation error will occur because of mutual exclusivity.
        if (ExemptUsers.Count == 0 && Users)
            parse.Remove("users");
        if (ExemptRoles.Count == 0 && Roles)
            parse.Remove("roles");

        var roleQuery =
            from role in ExemptRoles
            select role.Id.ToString();
        var userQuery = 
            from user in ExemptUsers
            select user.Id.ToString();

        return new JSON
        {
            { "parse", parse },
            { "roles", roleQuery },
            { "users", userQuery },
            { "replied_user", RepliedUser }
        };
    }
}

/// <summary>
/// Represents a poll on a <see cref="Message"/>.
/// </summary>
public record Poll
{
    // DOCS: https://discord.com/developers/docs/resources/poll#poll-object-poll-object-structure
    
    /// <summary>
    /// The question of the poll.
    /// </summary>
    [JsonIgnore]
    public string Question
    {
        get => _question.Text!;
        set => _question.Text = value;
    }
    [JsonProperty("question")] private readonly PollMedia _question;

    /// <summary>
    /// Each of the answers available in the poll, up to 10.
    /// </summary>
    [JsonProperty("answers")]
    public List<PollAnswer> Answers { get; set; }

    /// <summary>
    /// When the poll ends.
    /// </summary>
    [JsonProperty("expiry")]
    public DateTime? Expires { get; init; }
    [JsonProperty("duration")] internal int _duration;

    /// <summary>
    /// Whether a user can select multiple answers.
    /// </summary>
    [JsonProperty("allow_multiselect")]
    public bool IsMultiselectAllowed { get; set; }

    /// <summary>
    /// The layout type of the poll.
    /// </summary>
    [JsonProperty("layout_type")]
    public PollLayout Layout { get; set; }

    /// <summary>
    /// The results of the poll.
    /// </summary>
    [JsonProperty("results")]
    public PollResults? Results { get; init; }

    #region CUSTOM

    /// <summary>
    /// Your bot instance.
    /// </summary>
    public Bot Bot { get; internal set; } = null!;

    /// <summary>
    /// Message the poll is attached to.
    /// </summary>
    public Message Message { get; internal set; } = null!;
    
    #endregion
    
    /// <summary>
    /// Initializes a new poll instance.
    /// </summary>
    /// <param name="question">The question of the poll.</param>
    /// <param name="answers">Each of the answers available in the poll, up to 10.</param>
    /// <param name="expires">When the poll will close. 1 hour minimum, 32 days maximum.</param>
    /// <param name="allowMultiselect">Whether a user can select multiple answers.</param>
    /// <param name="layout">The layout type of the poll.</param>
    public Poll(string question, IEnumerable<PollAnswer> answers, TimeSpan expires, bool allowMultiselect = false,
        PollLayout layout = PollLayout.Default)
    {
        _question = new PollMedia(question);
        Question = _question.Text!;
        Answers = answers.ToList();
        _duration = GetDuration(expires);
        IsMultiselectAllowed = allowMultiselect;
        Layout = layout;
    }

    /// <summary>
    /// A more simple way to initialize a new poll instance. By default, <see cref="IsMultiselectAllowed"/> is <c>false</c>
    /// and <see cref="Layout"/> is <see cref="PollLayout.Default"/>.
    /// </summary>
    /// <param name="question">The question of the poll.</param>
    /// <param name="answers">Each of the answers available in the poll as a simple string, up to 10.</param>
    /// <param name="expires">When the poll will close. 1 hour minimum, 32 days maximum.</param>
    public Poll(string question, IEnumerable<string> answers, TimeSpan expires)
    {
        _question = new PollMedia(question);
        Question = _question.Text!;
        Answers = answers.Select(ans => new PollAnswer(new PollMedia(ans))).ToList();
        _duration = GetDuration(expires);
        IsMultiselectAllowed = false;
        Layout = PollLayout.Default;
    }

    [JsonConstructor]
    internal Poll(PollMedia question, List<PollAnswer> answers)
    {
        _question = question;
        Answers = answers;
    }
    
    /// <summary>
    /// Retrieve an answer.
    /// </summary>
    /// <param name="id">Answer ID.</param>
    /// <returns>The answer matching the provided ID, or <c>null</c> if not found.</returns>
    public PollAnswer? GetAnswer(int id) => 
        Answers.FirstOrDefault(a => a.Id == id);
    
    /// <summary>
    /// Users that voted for the provided answer.
    /// </summary>
    /// <param name="answer">Answer to check.</param>
    /// <param name="amount">Amount of users to return, max 100 per iteration.</param>
    /// <param name="after">Retrieve users after the provided date.</param>
    /// <returns>The requested amount of voters (users).</returns>
    public async IAsyncEnumerable<ICollection<User>> VotersAsync(PollAnswer answer, int? amount = 100, DateTime? after = null)
    {
        const int indefinite = -1;
        var remaining = amount ?? indefinite;
    
        var afterSnowflakeTime = after is not null ? Util.DateTimeToSnowflake(after.Value) : 0;
        var hasMore = true;
        var yielded = new List<User>();
    
        do
        {
            yielded.Clear();
            var requestAmount = remaining == indefinite ? 100 : Math.Min(remaining, 100);
            var users = await Bot._rest.GetAnswerVotersAsync(Message.ChannelId, Message.Id, answer.Id!.Value,
                afterSnowflakeTime, requestAmount);
            if (users.Count < 100)
                hasMore = false;
    
            foreach (var user in users)
            {
                yielded.Add(user);
                if (remaining == indefinite) continue;
    
                remaining -= 1;
                if (remaining == 0)
                    hasMore = false;
            }

            if (users.Count > 0)
            {
                afterSnowflakeTime = users.Last().Id;
                yield return yielded;
            }
            else
                yield break;
        } while (hasMore);
    }
    
    /// <summary>
    /// End the poll. You cannot end polls from other users.
    /// </summary>
    /// <returns>Message that the poll was attached to.</returns>
    public async Task<Message> EndAsync() => 
        await Bot._rest.EndPollAsync(Message.ChannelId, Message.Id);

    private static int GetDuration(TimeSpan expires)
    {
        var now = DateTimeOffset.UtcNow;
        var future = now.Add(expires);
        return (int)(future - now).TotalHours;
    }
}

/// <summary>
/// Represents various <see cref="Poll"/> values.
/// </summary>
public record PollMedia
{
    // DOCS: https://discord.com/developers/docs/resources/poll#poll-media-object
    
    /// <summary>
    /// The text of the field.
    /// </summary>
    [JsonProperty("text")]
    public string? Text { get; set; }

    /// <summary>
    /// The emoji of the field.
    /// </summary>
    [JsonProperty("emoji")]
    public PartialEmoji? Emoji { get; set; }

    /// <summary>
    /// Initializes a new poll media instance.
    /// </summary>
    /// <param name="text">Text of the media.</param>
    /// <param name="emoji">Emoji of the media.</param>
    public PollMedia(string text, PartialEmoji? emoji = null)
    {
        Text = text;
        Emoji = emoji;
    }
}

/// <summary>
/// Represents an answer in a <see cref="Poll"/>.
/// </summary>
public record PollAnswer
{
    // DOCS: https://discord.com/developers/docs/resources/poll#poll-answer-object
    
    /// <summary>
    /// The ID of the answer.
    /// </summary>
    [JsonProperty("answer_id")]
    public int? Id { get; private set; }

    /// <summary>
    /// The data of the answer.
    /// </summary>
    [JsonProperty("poll_media")]
    public PollMedia Media { get; set; }

    /// <summary>
    /// Initializes a new poll answer instance.
    /// </summary>
    /// <param name="answer">The media which relates to the answer text/emoji.</param>
    public PollAnswer(PollMedia answer)
    {
        Media = answer;
    }
}

/// <summary>
/// Represents the number of votes for each <see cref="PollAnswer"/>.
/// </summary>
public record PollResults
{
    // DOCS: https://discord.com/developers/docs/resources/poll#poll-results-object
    
    /// <summary>
    /// Whether the votes have been precisely counted.
    /// </summary>
    [JsonProperty("is_finalized")]
    public bool IsFinalized { get; private set; }

    /// <summary>
    /// The counts for each answer.
    /// </summary>
    [JsonProperty("answer_counts")]
    public IReadOnlyCollection<PollAnswerCount> AnswerCounts { get; private set; } = [];
    
    private PollResults() { }
}

/// <summary>
/// Represents the count for each <see cref="PollAnswer"/>.
/// </summary>
public record PollAnswerCount
{
    // DOCS: https://discord.com/developers/docs/resources/poll#poll-results-object-poll-answer-count-object-structure
    
    /// <summary>
    /// The <see cref="PollAnswer.Id"/>.
    /// </summary>
    [JsonProperty("id")]
    public int Id { get; private set; }

    /// <summary>
    /// The number of votes for this answer.
    /// </summary>
    [JsonProperty("count")]
    public int Count { get; private set; }

    /// <summary>
    /// Whether the current user voted for this answer.
    /// </summary>
    [JsonProperty("me_voted")]
    public bool MeVoted { get; private set; }
    
    private PollAnswerCount() { }
}

/// <summary>
/// Represents a <see cref="Poll"/> layout.
/// </summary>
public enum PollLayout
{
    /// <summary>
    /// Default layout type.
    /// </summary>
    Default = 1
}
